// This file is machine-generated - edit at your own risk.

'use server';
/**
 * @fileOverview This file defines a Genkit flow for enhancing a user's biography using AI.
 *
 * - enhanceBio - A function that takes user details and generates an enhanced bio.
 * - EnhanceBioInput - The input type for the enhanceBio function.
 * - EnhanceBioOutput - The return type for the enhanceBio function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const EnhanceBioInputSchema = z.object({
  name: z.string().describe('The user\'s name.'),
  age: z.number().describe('The user\'s age.'),
  occupation: z.string().describe('The user\'s occupation.'),
  contactInformation: z.string().describe('The user\'s contact information.'),
  shortBio: z.string().describe('The user\'s current short bio.'),
  skills: z.array(z.string()).describe('A list of the user\'s skills.'),
  projectDescriptions: z.array(z.string()).describe('A list of project descriptions.'),
});
export type EnhanceBioInput = z.infer<typeof EnhanceBioInputSchema>;

const EnhanceBioOutputSchema = z.object({
  enhancedBio: z.string().describe('The enhanced bio generated by the AI.'),
});
export type EnhanceBioOutput = z.infer<typeof EnhanceBioOutputSchema>;

export async function enhanceBio(input: EnhanceBioInput): Promise<EnhanceBioOutput> {
  return enhanceBioFlow(input);
}

const enhanceBioPrompt = ai.definePrompt({
  name: 'enhanceBioPrompt',
  input: {
    schema: z.object({
      name: z.string().describe('The user\'s name.'),
      age: z.number().describe('The user\'s age.'),
      occupation: z.string().describe('The user\'s occupation.'),
      contactInformation: z.string().describe('The user\'s contact information.'),
      shortBio: z.string().describe('The user\'s current short bio.'),
      skills: z.array(z.string()).describe('A list of the user\'s skills.'),
      projectDescriptions: z.array(z.string()).describe('A list of project descriptions.'),
    }),
  },
  output: {
    schema: z.object({
      enhancedBio: z.string().describe('The enhanced bio generated by the AI.'),
    }),
  },
  prompt: `You are a professional resume writer. You are helping a user write a professional bio.

  Here are the user's details:
  Name: {{{name}}}
  Age: {{{age}}}
  Occupation: {{{occupation}}}
  Contact Information: {{{contactInformation}}}
  Short Bio: {{{shortBio}}}
  Skills: {{#each skills}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  Project Descriptions: {{#each projectDescriptions}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

  Please generate a personalized and engaging summary/bio for the user's portfolio based on the details provided. The bio should be professional and highlight the user's key skills and experiences. The bio should be approximately 100-150 words.
  `,
});

const enhanceBioFlow = ai.defineFlow<
  typeof EnhanceBioInputSchema,
  typeof EnhanceBioOutputSchema
>({
  name: 'enhanceBioFlow',
  inputSchema: EnhanceBioInputSchema,
  outputSchema: EnhanceBioOutputSchema,
},
async input => {
  const {output} = await enhanceBioPrompt(input);
  return output!;
});
